"""Error codes enum."""
from enum import StrEnum


class ErrorCode(StrEnum):
    VALIDATION_ERROR = "VALIDATION_ERROR"
    NOT_FOUND = "NOT_FOUND"
    CONFIGURATION_ERROR = "CONFIGURATION_ERROR"
    WORKFLOW_ERROR = "WORKFLOW_ERROR"
    LLM_PROVIDER_ERROR = "LLM_PROVIDER_ERROR"
    STATE_STORAGE_ERROR = "STATE_STORAGE_ERROR"
    INTERNAL_ERROR = "INTERNAL_ERROR"
